### ISSUE TITLE
Actions and holdings overlapping

### ISSUE THREAD

**Issue by MFalletta** [rism-digital/rism.info#1731]
Die Seitenleiste in der Datensatzansicht überdeckt beim Scrollen die Holdings der Drucke (Musikdruck Haupteintrag). 
Bei Drucken mit vielen Exemplaren sieht man nicht alle https://muscat.rism.info/admin/sources/990045865 (s. Abb.). Bei Drucken mit wenigen Exemplaren, sieht es so aus, als wenn gar keine vorhanden wären (vgl. https://muscat.rism.info/admin/sources/1001184812). Hier sieht man die Hoodings erst, wenn man nach unten scrollt. 

![holdings actions](https://user-images.githubusercontent.com/18736235/149906924-edb14c4d-67e2-4702-802e-ea47ed754316.png)

**Comment by BaMikusi** [comment]
This should be among the Muscat issues, so I am closing it here and open it over there.
