### ISSUE TITLE
Add redirects to broken links

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/rism.info#282]
Is it OK if I add dead links here that I find out in the wild?

http://www.rism.info/en/home/newsdetails/select/self_representation/article/2/new-rism-sigla-search-on-risminfo.html
to 
https://rism.info/new_at_rism/2011/11/29/new-rism-sigla-search-on-risminfo.html

http://www.rism.info/en/home/newsdetails/browse/3/article/64/printed-music-ai-and-bi-now-in-risms-online-catalog.html
to
https://rism.info/new_at_rism/2015/05/21/printed-music-ai-and-bi-now-in-risms-online.html

http://www.rism.info/en/publications/annual-reports/2010/
to
https://rism.info/publications/annual-reports/2010.html

**Comment by jenniferward** [comment]
http://www.rism.info/en/home/newsdetails/select/self_representation/article/64/trnka-who-mistaken-attributions-and-their-effects.html
to
https://rism.info/new_at_rism/2018/08/06/trnkawho-mistaken-attributions-and-their-effects.html

**Comment by jenniferward** [comment]
http://www.rism.info/en/home/newsdetails/select/rism_online_catalog/article/2/search-strategies-for-printed-music.html
to
https://rism.info/rism_online_catalog/2019/03/25/search-strategies-for-printed-music.html

http://www.rism.info/en/home/newsdetails/article/2/revising-records-for-post-1600-printed-anthologies-there-is-an-end-in-sight.html 
to
https://rism.info/new_at_rism/2020/07/02/revising-records-for-post1600-printed-anthologies.html

http://www.rism.info/en/home/newsdetails/select/new_publications/article/64/17th-century-printed-anthologies-the-first-decade-is-now-online.html
to
https://rism.info/new_at_rism/2019/03/28/17thcentury-printed-anthologies-the-first-decade.html

http://www.rism.info/en/home/newsdetails/select/electronic_resources/article/2/printed-music-to-1550-a-report-from-the-central-office-ii.html
to
https://rism.info/new_at_rism/2018/04/19/printed-music-to-1550-a-report-from-the-central.html

http://www.rism.info/index.php?id=724 
to
https://www.rism.info/working-groups/mexico/home.html

http://www.rism.info/en/home/newsdetails/select/self_representation/article/64/rism-bi-recueils-imprimes-xvie-siecles-version-20-a-report-from-the-central-office.html
to
https://rism.info/new_at_rism/2017/11/27/rism-bi-recueils-imprim%C3%A9s-xvie-si%C3%A8cles-version-20.html

**Comment by jenniferward** [comment]
http://www.rism.info/en/publications.html#c36
to
https://rism.info/publications.html#series-a-inventories-of-musical-sources

http://www.rism.info/en/publications/#c2619
to
https://rism.info/publications.html#series-b-bibliographies-organized-by-topic

http://www.rism.info/en/home/newsdetails/article/2/2019-upgrade-of-the-rism-catalog.html
to
https://rism.info/rism_online_catalog/2019/09/09/2019-upgrade-of-the-rism-catalog.html

**Comment by jenniferward** [comment]
http://www.rism.info/en/home/newsdetails/article/64/new-version-of-the-rism-online-catalog-1.html
to
https://rism.info/new_at_rism/2018/07/16/new-version-of-the-rism-online-catalog.html

http://www.rism.info/en/home/newsdetails/select/rism_online_catalog/article/2/new-version-of-the-rism-online-catalog.html
to
https://rism.info/new_at_rism/2014/04/10/new-version-of-the-rism-online-catalog.html

http://www.rism.info/en/home/newsdetails/select/rism_online_catalog/article/2/new-version-of-risms-online-catalog-with-incipit-search-released.html
to
https://rism.info/new_publications/2011/04/11/new-version-of-risms-online-catalog-with-incipit.html

http://www.rism.info/en/home/newsdetails/select/rism_online_catalog/article/2/new-online-music-catalogue-over-700000-entries.html
to
https://rism.info/in_the_news/2010/06/30/new-online-music-catalogue-over-700000-entries.html

http://www.rism.info/en/community/muscat.html#c3449
to
https://rism.info/community/muscat/tutorials.html

http://www.rism.info/en/home/newsdetails/article/64/new-projects-with-risms-music-incipts.html
to
https://rism.info/electronic_resources/2019/02/04/new-projects-with-risms-music-incipts.html

http://www.rism.info/en/home/newsdetails/select/rism_online_catalog/article/2/searching-for-people-in-the-new-rism-catalog.html
to
https://rism.info/rism_online_catalog/2018/10/22/searching-for-people-in-the-new-rism-catalog.html

http://www.rism.info/en/service/feedback.html
to
https://rism.info/service/feedback.html

http://www.rism.info/en/organisation/project-structure-and-funding.html
to
https://rism.info/organization/project-structure.html

**Comment by ahankinson** [comment]
I've updated the site with the new redirects. Unfortunately, and redirect with a hash parameter is not able to be redirected -- the server never sees this part of the URL, so it can't redirect it. I've marked these with strikethroughs above.

**Comment by jenniferward** [comment]
Thanks! Hope it's ok to just reopen this as I find new ones. This will be the last for the year.
http://www.rism.info/en/home/newsdetails/article/64/listen-to-the-worlds-oldest-piano.html to

https://rism.info/rediscovered/2014/05/28/listen-to-the-worlds-oldest-piano.html

**Comment by ahankinson** [comment]
Actually, it would be better to open new issues and then assign me to it for any new ones. 

You can also leave off the "http://www.rism.info" and "https://rism.info" bits; ideally the format would be old_url <space> new_url: 

```
/en/home/newsdetails/article/64/listen-to-the-worlds-oldest-piano.html /rediscovered/2014/05/28/listen-to-the-worlds-oldest-piano.html
```

**Comment by ahankinson** [comment]
☝️ That message means that I've fixed it in another repo; you can click that link to see the change.
