### ISSUE TITLE
News categories aren't visible?

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/rism.info#328]
I don't see where the News categories are visible when you are looking at a single news post, so the navigation points "Older/Newer in this category" don't make much sense. Am I missing something? 
The old website had the structure Category: TitleOfNews on the main page so it was always obvious where a post belonged.

**Comment by lpugin** [comment]
Fixed with https://github.com/rism-digital/rism-theme/commit/c4cc023bf74ca0a065db822dcdf84532c4036577
