### ISSUE TITLE
"Privacy Policy" in footer

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/rism.info#52]
I think the privacy policy https://stage.rism.info/organization/privacy-policy.html needs to be moved to the footer, next to the Impressum. It's currently under Organization but no one would look for it there, and since GDPR it is required.

**Comment by lpugin** [comment]
> next to the Impressum

There is not "Impressum". Do you mean "Disclaimer"? or "Contact us"?

**Comment by jenniferward** [comment]
Oh, even in German it's not "Impressum"? I wonder if that word should be visible, since it is a legal requirement for websites in Germany, and the English bits carry no weight.  Because of this legal requirement, I wouldn't mind having the word on the English pages. 

But yes, I would say it should be Privacy Policy and then Disclaimer/Impressum, as on the current page.
