### ISSUE TITLE
Add redirects to broken links

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/rism.info#601]
/home/newsdetails/article/64/bach-330-the-brandenburg-concerto-manuscript-at-the-library-of-congress.html /musical_anniversaries/2015/03/19/bach-330-the-brandenburg-concerto-manuscript-at.html

**Comment by jenniferward** [comment]
/en/home/newsdetails/article/64/diversity-in-rism.html  /library_collections/2020/10/26/diversity-in-rism.html

/en/home/newsdetails/article/64/introductory-muscat-workshops-in-november-full.html /events/2020/10/22/introductory-muscat-workshops-in-november-full.html

/en/home/newsdetails/article/64/printed-music-and-early-printed-books.html /new_at_rism/2020/10/15/printed-music-and-early-printed-books.html

/en/home/newsdetails/article/64/jenny-lind-at-200.html /musical_anniversaries/2020/10/05/jenny-lind-at-200.html /musical_anniversaries/2020/10/05/jenny-lind-at-200.html

/en/home/newsdetails/article/64/help-rism-identify-unknown-languages.htm /rism_online_catalog/2020/09/21/help-rism-identify-unknown-languages.html

/en/home/newsdetails/article/64/rism-projects-while-working-from-home.html /new_at_rism/2020/09/14/rism-projects-while-working-from-home.html

/en/home/newsdetails/article/64/rism-data-in-now-eromm.html /new_at_rism/2020/09/10/rism-data-in-now-eromm.html

/en/home/newsdetails/article/64/a-royal-library-king-ludwig-iis-music-collection.html /musical_anniversaries/2020/08/17/a-royal-library-king-ludwig-iis-music-collection.html

/en/home/newsdetails/article/64/lost-and-found-gottfried-kirchhoffs-labc-musical.html /rediscovered/2020/08/10/lost-and-found-gottfried-kirchhoffs-labc-musical.html

/en/home/newsdetails/article/64/10-years-of-the-rism-online-catalog-our-users.html /rism_online_catalog/2020/06/25/10-years-of-the-rism-online-catalog-our-users.html

/en/home/newsdetails/article/64/was-this-book-of-pleyel-sonatas-once-part-of-jane-austens-circle.html /library_collections/2020/06/18/was-this-book-of-pleyel-sonatas-once-part-of-jane.html

/en/home/newsdetails/article/64/free-access-to-fontes-artis-musicae-through-june-30.html /new_publications/2020/05/04/free-access-to-fontes-artis-musicae-through-june.html

/en/home/newsdetails/article/64/new-rism-tutorial-in-german.html /rism_online_catalog/2020/04/20/new-rism-tutorial-in-german.html

/en/home/newsdetails/article/64/rism-in-re3data.html /new_at_rism/2020/04/06/rism-in-re3data.html

/en/home/newsdetails/article/64/a-new-elise-discovery-sheds-light-on-famous-beethoven-work.html /rediscovered/2020/04/01/a-new-elise-discovery-sheds-light-on-famous.html

/en/home/newsdetails/article/64/first-rism-siglum-for-papua-new-guinea.html /new_at_rism/2020/03/23/first-rism-siglum-for-papua-new-guinea.html

/en/home/newsdetails/article/64/rism-central-office-temporarily-closed.html /new_at_rism/2020/03/18/rism-central-office-temporarily-closed.html

/en/home/newsdetails/article/64/rism-and-beethoven-and-the-19th-century.html /musical_anniversaries/2020/03/12/rism-and-beethoven-and-the-19th-century.html

/en/home/newsdetails/article/2/2020-not-just-beethoven.html /musical_anniversaries/2020/01/09/2020-not-just-beethoven.html

/en/home/newsdetails/select/rism_a_z/article/64/isabella-leonarda-1620-1704.html /rism_a_z/2016/04/07/isabella-leonarda-16201704.html

**Comment by jenniferward** [comment]
/en/sigla/ /community/sigla.html

**Comment by jenniferward** [comment]
@ahankinson Is there any discernible pattern in the URLs in my 2nd big comment above that can lead to an automated process for broken URLs? I'm afraid there will be many more with the /en/home/newsdetails/article/64 bit, and only a few of them currently redirect correctly.

**Comment by jenniferward** [comment]
Another related question! Our news posts include a column for old_url. Will these get redirected? Sometimes they work, but sometimes they don't. Example:  
https://github.com/rism-digital/rism.info/blob/staging/_posts/en/2018-01/2018-01-25-new-foncarism-project-in-mexico-city--foncarism.md

**Comment by ahankinson** [comment]
No, I can't see any pattern. The issue is that the categories didn't really exist on the old site, but now they're a fundamental part of the new URL. So while the old URL just has `/en/home/newsdetails/article/64/...` the new URL can vary with `/new_publications/` or `/library_collections` or /rediscovered`. So even if we could match the last bit (ending with `.html`) there's not really a good way to match the first bit of the URL. 

As far as I know the `old_url` was used during the export to generate the first redirect list, but it's no longer needed or used. It was just a bit of metadata so that we could know where that page came from when we migrated the content.

**Comment by ahankinson** [comment]
Are you getting complaints about these URLs? Where and how are they referenced?

**Comment by jenniferward** [comment]
No, personally I have not been receiving complaints about the URLs. But I know they are floating out there, like on social media or in publications, Wikipedia, etc. I maintain a partial list of news posts (for my records) but now most the links do not work. That's where the bulk of the 2nd comment came from.

**Comment by ahankinson** [comment]
I note that the brandenburg concerto link is in two different sections: 'musical anniversaries' for the English, and "library collections" for the german... will this be corrected?
