### ISSUE TITLE
Double news

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/rism.info#70]
I'm a bit confused about this post:
New
https://github.com/rism-digital/rism.info/blob/staging/_posts/en/2017-03/2017-03-08-international-womens-day-women-composers-in.md

https://stage.rism.info/events/2017/03/08/international-womens-day-women-composers-in.html

(Old
http://www.rism.info/en/home/newsdetails/article/64/international-womens-day-women-composers-in-rism.html )

There seems to be a "Musical Anniversary" post underneath it. There is also a "See more at" with a link which we never write. 
Lines 29-70 should not be there. Can I just delete it, or is there an underlying issue?

**Comment by lpugin** [comment]
@xhero do you have an idea about what happened there?

**Comment by ahankinson** [comment]
This seems to still be an issue. Probably best just to delete the problem, now that the site is live.

**Comment by jenniferward** [comment]
Agree. Will do.
