### ISSUE TITLE
Change URL for news?

### ISSUE THREAD

**Issue by jenniferward** [rism-digital/rism.info#86]
This URL has Chinese characters in it
https://stage.rism.info/in_the_news/2015/03/12/from-the-first%E6%9C%80%E5%88%9D-to-the-best%E6%9C%80%E9%AB%98-ewha-music.html

![image](https://user-images.githubusercontent.com/18663291/101638100-f0a1b180-3a2d-11eb-9e7a-4d877b7570aa.png)

I'm wondering if the URL should be simplified.

**Comment by lpugin** [comment]
You can rename the file

![image](https://user-images.githubusercontent.com/689412/101642490-5d6b7a80-3a33-11eb-9b16-30503790fc4d.png)

Make sure all translation files have exactly the same file name, otherwise the news will be duplicated.

**Comment by jenniferward** [comment]
I thought I did, but something went wrong. They are both showing up with the English text now:
https://stage.rism.info/de/in_the_news/2015/03/12/from-the-first-to-the-best-ewha-music.html

**Comment by lpugin** [comment]
No problem. You simply forgot the date (2015-03-12-) at the beginning of the beginning of the German filename. I fixed it.
